/**
 * Stable root import for `micro509`.\
 * Re-exports the common certificate, parsing, verification, revocation, key, and PKCS
 * workflows from one package entrypoint.
 *
 * Reach for this module when you want the default workflow-first package surface.
 * Use domain entrypoints such as `micro509/x509`, `micro509/verify`, and
 * `micro509/revocation` when you need exhaustive advanced types.
 *
 * The root export is organized around common PKI flows:
 *
 * - create certificates, CSRs, CRLs, OCSP responses, PKCS#7, and PFX artifacts
 * - parse DER or PEM inputs into typed certificate and request shapes
 * - verify certificate chains, service identities, CRLs, OCSP, and signed data
 * - import, export, generate, and encrypt key material with WebCrypto-safe algorithms
 * - work with the common extension inputs, revocation evidence, and validation results
 *
 * Advanced PKCS#12 MAC plumbing, signature profile tuning, and other domain-specific helper
 * types stay in their owner domains instead of being headlined here.
 *
 * @example
 * ```ts
 * import {
 * 	createSelfSignedCertificate,
 * 	parseCertificatePem,
 * 	unwrap,
 * 	verifyCertificateChain,
 * } from 'micro509';
 *
 * const { certificate } = await createSelfSignedCertificate({
 * 	subject: { commonName: 'example.com' },
 * 	algorithm: { kind: 'ecdsa', curve: 'P-256' },
 * });
 *
 * const parsed = unwrap(parseCertificatePem(certificate.pem));
 * // parsed.subject.values.commonName === 'example.com'
 *
 * const result = await verifyCertificateChain({
 * 	leaf: certificate.pem,
 * 	roots: [certificate.pem],
 * 	allowSelfSignedLeaf: true,
 * });
 * // result.ok === true
 * ```
 *
 * @example
 * ```ts
 * import {
 * 	generateKeyPair,
 * 	parseCertificateSigningRequestPem,
 * 	createCertificateSigningRequest,
 * 	unwrap,
 * } from 'micro509';
 *
 * const keyPair = await generateKeyPair({ kind: 'ecdsa', curve: 'P-256' });
 * const csr = await createCertificateSigningRequest({
 * 	subject: { commonName: 'example.com' },
 * 	publicKey: keyPair.publicKey,
 * 	signerPrivateKey: keyPair.privateKey,
 * });
 *
 * const parsed = unwrap(parseCertificateSigningRequestPem(csr.pem));
 * // parsed.subject.values.commonName === 'example.com'
 * ```
 *
 * @module micro509
 */

export type {
	DecryptRsaOaepErrorCode,
	DecryptRsaOaepFailure,
	DecryptRsaOaepResult,
	EcKeyAlgorithmInput,
	EcNamedCurve,
	Ed25519KeyAlgorithmInput,
	EncryptedPkcs8Options,
	EncryptRsaOaepErrorCode,
	EncryptRsaOaepFailure,
	EncryptRsaOaepResult,
	ImportEcKeyInput,
	ImportEd25519KeyInput,
	ImportEncryptedKeyErrorCode,
	ImportEncryptedKeyFailure,
	ImportEncryptedKeyOptions,
	ImportEncryptedKeyResult,
	ImportKeyErrorCode,
	ImportKeyFailure,
	ImportKeyResult,
	ImportRsaKeyInput,
	KdfLimitOptions,
	KeyAlgorithmInput,
	KeyPairMaterial,
	LegacyPemEncryptionOptions,
	Pbes2Parameters,
	PrivateKeyImportInput,
	PublicKeyImportInput,
	RsaHash,
	RsaKeyAlgorithmInput,
	RsaOaepOptions,
	RsaScheme,
	RsaSignatureScheme,
} from '#micro509/keys';
export {
	decryptRsaOaep,
	decryptRsaOaepOrThrow,
	derivePublicKey,
	encryptRsaOaep,
	encryptRsaOaepOrThrow,
	exportBinaryBase64,
	exportEncryptedPkcs1Pem,
	exportEncryptedPkcs8Der,
	exportEncryptedPkcs8Pem,
	exportEncryptedSec1Pem,
	exportPkcs1Der,
	exportPkcs1Pem,
	exportPkcs8Der,
	exportPkcs8Pem,
	exportPrivateJwk,
	exportPublicJwk,
	exportSec1Der,
	exportSec1Pem,
	exportSpkiDer,
	exportSpkiPem,
	generateKeyPair,
	importEncryptedPkcs1Pem,
	importEncryptedPkcs1PemOrThrow,
	importEncryptedPkcs8Der,
	importEncryptedPkcs8DerOrThrow,
	importEncryptedPkcs8Pem,
	importEncryptedPkcs8PemOrThrow,
	importEncryptedSec1Pem,
	importEncryptedSec1PemOrThrow,
	importPkcs1Der,
	importPkcs1DerOrThrow,
	importPkcs1Pem,
	importPkcs1PemOrThrow,
	importPkcs8Base64,
	importPkcs8Base64OrThrow,
	importPkcs8Der,
	importPkcs8DerOrThrow,
	importPkcs8Pem,
	importPkcs8PemOrThrow,
	importPrivateJwk,
	importPrivateJwkOrThrow,
	importPublicJwk,
	importPublicJwkOrThrow,
	importSec1Der,
	importSec1DerOrThrow,
	importSec1Pem,
	importSec1PemOrThrow,
	importSpkiBase64,
	importSpkiBase64OrThrow,
	importSpkiDer,
	importSpkiDerOrThrow,
	importSpkiPem,
	importSpkiPemOrThrow,
	inspectEncryptedPkcs8Der,
} from '#micro509/keys';

export type {
	CategorizedPemBlocks,
	CategorizePemBlocksResult,
	PemBlock,
	PemDecodeResult,
	PemErrorCode,
	PemFailure,
	SplitPemBlocksResult,
} from '#micro509/pem';
export {
	categorizePemBlocks,
	categorizePemBlocksOrThrow,
	pemDecode,
	pemDecodeOrThrow,
	pemEncode,
	splitPemBlocks,
	splitPemBlocksOrThrow,
} from '#micro509/pem';

export type {
	CreatePfxErrorCode,
	CreatePfxFailure,
	CreatePfxInput,
	CreatePfxResult,
	CreatePkcs7CertBagErrorCode,
	CreatePkcs7CertBagFailure,
	CreatePkcs7CertBagResult,
	CreatePkcs7SignedDataErrorCode,
	CreatePkcs7SignedDataFailure,
	CreatePkcs7SignedDataInput,
	CreatePkcs7SignedDataResult,
	ParsedCertificateChoice,
	ParsedPfx,
	ParsedPfxAttribute,
	ParsedPfxBag,
	ParsedPfxBagAttributes,
	ParsedPkcs7SignedData,
	ParsedPkcs7SignerInfo,
	ParsedPkcs7SignerInfoBase,
	ParsedPkcs12MacData,
	ParsedSignerIdentifier,
	ParsePfxErrorCode,
	ParsePfxFailure,
	ParsePfxOptions,
	ParsePfxResult,
	ParsePkcs7CertBagResult,
	ParsePkcs7ErrorCode,
	ParsePkcs7Failure,
	ParsePkcs7SignedDataResult,
	ParsePkcs12MacDataErrorCode,
	ParsePkcs12MacDataFailure,
	ParsePkcs12MacDataOptions,
	ParsePkcs12MacDataResult,
	PfxBagAttributesInput,
	PfxCertificateBagInput,
	PfxCertificateSource,
	PfxEncryptionOptions,
	PfxMaterial,
	PfxPrivateKeyBagInput,
	PfxPrivateKeySource,
	Pkcs7CertBagMaterial,
	Pkcs7CertificateSource,
	Pkcs7SignedDataMaterial,
	Pkcs7Signer,
	Pkcs12MacOptions,
	VerifiedPkcs7Signer,
	VerifyPkcs7SignedDataErrorCode,
	VerifyPkcs7SignedDataFailure,
	VerifyPkcs7SignedDataOptions,
	VerifyPkcs7SignedDataResult,
} from '#micro509/pkcs';
export {
	createPfx,
	createPkcs7CertBag,
	createPkcs7SignedData,
	parsePfxDer,
	parsePfxPem,
	parsePkcs7CertBagDer,
	parsePkcs7CertBagPem,
	parsePkcs7SignedDataDer,
	parsePkcs7SignedDataPem,
	verifyPkcs7SignedData,
} from '#micro509/pkcs';

export type {
	ErrorResult,
	IndexedErrorResult,
	IndexedMicro509Error,
	Micro509Error,
	Result,
	ResultError,
} from '#micro509/result';
export { isResultError, unwrap, unwrapOr } from '#micro509/result';

export type {
	CertificateRevocationListMaterial,
	CertificateRevocationStatus,
	CheckCertificateRevocationAgainstCrlErrorCode,
	CheckCertificateRevocationAgainstCrlFailure,
	CheckCertificateRevocationAgainstCrlFailureDetails,
	CheckCertificateRevocationAgainstCrlGoodValue,
	CheckCertificateRevocationAgainstCrlInput,
	CheckCertificateRevocationAgainstCrlResult,
	CheckCertificateRevocationAgainstCrlRevokedValue,
	CheckCertificateRevocationAgainstCrlValue,
	CheckCertificateRevocationErrorCode,
	CheckCertificateRevocationFailureDetails,
	CheckCertificateRevocationInput,
	CheckCertificateRevocationResult,
	CheckCertificateRevocationValue,
	CheckChainRevocationInput,
	CheckChainRevocationResult,
	CheckChainRevocationValue,
	ConfiguredOcspResponder,
	ConfiguredOcspResponderCertificate,
	CreateCertificateRevocationListInput,
	CreateOcspCertStatusInput,
	CreateOcspRequestInput,
	CreateOcspRequestItemInput,
	CreateOcspResponseInput,
	CreateOcspSingleResponseInput,
	CrlApplicabilityFailureReason,
	CrlCertificateSource,
	CrlEncoderErrorCode,
	CrlSource,
	IssuingDistributionPoint,
	IssuingDistributionPointBase,
	IssuingDistributionPointForAttributeCerts,
	IssuingDistributionPointForCaCerts,
	IssuingDistributionPointForUserCerts,
	OcspCertificateSource,
	OcspCertStatus,
	OcspEncoderErrorCode,
	OcspHashAlgorithm,
	OcspRequestMaterial,
	OcspRequestSource,
	OcspResponderCandidate,
	OcspResponderRevocationPolicy,
	OcspResponderSource,
	OcspResponseMaterial,
	OcspResponseSource,
	OcspResponseStatus,
	ParseCertificateRevocationListErrorCode,
	ParseCertificateRevocationListFailure,
	ParseCertificateRevocationListResult,
	ParsedCertificateRevocationList,
	ParsedIssuingDistributionPoint,
	ParsedIssuingDistributionPointBase,
	ParsedIssuingDistributionPointScope,
	ParsedOcspCertId,
	ParsedOcspCertStatus,
	ParsedOcspRequest,
	ParsedOcspResponderId,
	ParsedOcspResponse,
	ParsedOcspSingleResponse,
	ParsedRevokedCertificate,
	ParseOcspRequestErrorCode,
	ParseOcspRequestFailure,
	ParseOcspRequestResult,
	ParseOcspResponseErrorCode,
	ParseOcspResponseFailure,
	ParseOcspResponseResult,
	ResolveOcspResponderCandidatesInput,
	RevocationCertificateSource,
	RevocationCheckGoodValue,
	RevocationCheckIndeterminateValue,
	RevocationCheckRevokedValue,
	RevocationCrlEvidenceInput,
	RevocationEvidenceInput,
	RevocationEvidenceKind,
	RevocationExecutionError,
	RevocationIndeterminateEvidence,
	RevocationIndeterminateReason,
	RevocationIndeterminateReasonCode,
	RevocationOcspEvidenceInput,
	RevocationPolicy,
	RevocationReason,
	RevocationSource,
	RevocationStatus,
	RevokedCertificateInput,
	TrustedOcspResponder,
	ValidateCertificateRevocationListFailure,
	ValidateCertificateRevocationListInput,
	ValidateCertificateRevocationListResult,
	ValidateOcspResponseErrorCode,
	ValidateOcspResponseFailure,
	ValidateOcspResponseInput,
	ValidateOcspResponseResult,
	VerifyCertificateRevocationListSignatureFailure,
	VerifyCertificateRevocationListSignatureResult,
	VerifyOcspResponseSignatureFailure,
	VerifyOcspResponseSignatureResult,
} from '#micro509/revocation';
export {
	checkCertificateRevocation,
	checkCertificateRevocationAgainstCrl,
	checkChainRevocation,
	createCertificateRevocationList,
	createOcspRequest,
	createOcspResponse,
	getCertificateOcspResponderUris,
	hasOcspNoCheckExtension,
	isCertificateRevoked,
	parseCertificateRevocationListDer,
	parseCertificateRevocationListDerOrThrow,
	parseCertificateRevocationListPem,
	parseCertificateRevocationListPemOrThrow,
	parseOcspRequestDer,
	parseOcspRequestDerOrThrow,
	parseOcspRequestPem,
	parseOcspRequestPemOrThrow,
	parseOcspResponseDer,
	parseOcspResponseDerOrThrow,
	parseOcspResponsePem,
	parseOcspResponsePemOrThrow,
	REVOCATION_INDETERMINATE_REASON_CODES,
	REVOCATION_INDETERMINATE_REASONS,
	resolveOcspResponderCandidates,
	revocationReasonFromCode,
	validateCertificateRevocationList,
	validateOcspResponse,
	verifyCertificateRevocationListSignature,
	verifyOcspResponseSignature,
} from '#micro509/revocation';

export type {
	BuildCandidatePathInput,
	BuildCandidatePathResult,
	CandidatePath,
	CertificateSource,
	ChainRevocationInput,
	ConstrainedPolicy,
	CsrSource,
	DnsServiceIdentityInput,
	EkuCheckFailure,
	EkuCheckPurpose,
	EkuCheckResult,
	InitialNameConstraintsInput,
	IpServiceIdentityInput,
	MatchServiceIdentityErrorCode,
	MatchServiceIdentityFailure,
	MatchServiceIdentityFailureDetails,
	MatchServiceIdentityFailureResult,
	MatchServiceIdentityInput,
	MatchServiceIdentityResult,
	MatchServiceIdentitySuccess,
	PolicyValidationInput,
	PolicyValidationOutcome,
	ServiceIdentityInput,
	ServiceIdentityType,
	SrvServiceIdentityInput,
	TrustAnchor,
	UriServiceIdentityInput,
	ValidateCandidatePathInput,
	ValidateCandidatePathResult,
	ValidateCandidatePathSuccess,
	ValidateForCaInput,
	ValidateForCodeSigningInput,
	ValidateForTlsClientInput,
	ValidateForTlsServerInput,
	VerifiedCertificateChain,
	VerifyCertificateChainInput,
	VerifyChainFailure,
	VerifyChainResult,
	VerifyErrorCode,
	VerifyFailureDetails,
	VerifyPurpose,
	VerifyRequestFailure,
	VerifyRequestResult,
} from '#micro509/verify';
export {
	buildCandidatePath,
	checkExtendedKeyUsage,
	isSelfIssuedCertificate,
	matchCertificateServiceIdentity,
	matchServiceIdentity,
	trustAnchorFromCertificate,
	VERIFY_ERROR_CODES,
	validateCandidatePath,
	validateForCa,
	validateForCodeSigning,
	validateForTlsClient,
	validateForTlsServer,
	verifyCertificateChain,
	verifyCertificateSigningRequest,
} from '#micro509/verify';

export type {
	AuthorityInformationAccess,
	AuthorityInformationAccessInput,
	BasicConstraints,
	CertificateExtensionsInput,
	CertificateFingerprint,
	CertificateFingerprintAlgorithm,
	CertificateFingerprintSource,
	CertificateMaterial,
	CertificatePolicies,
	CreateCertificateErrorCode,
	CreateCertificateInput,
	CreateCsrInput,
	CreateSelfSignedCertificateBase,
	CreateSelfSignedCertificateInput,
	CsrMaterial,
	DecodedExtensionMap,
	DecodedExtensionValue,
	DistributionPoint,
	DistributionPointName,
	ExtendedKeyUsage,
	ExtensionDecoder,
	ExtensionDecoderMap,
	ExtensionEncoderErrorCode,
	GeneralName,
	GeneralSubtree,
	InhibitAnyPolicy,
	KeyUsage,
	MatchCertificatePrivateKeyErrorCode,
	MatchCertificatePrivateKeyFailure,
	MatchCertificatePrivateKeyFailureResult,
	MatchCertificatePrivateKeyResult,
	MatchCertificatePrivateKeySuccess,
	NameAttribute,
	NameConstraintForm,
	NameConstraints,
	NameEncoderErrorCode,
	NameFieldKey,
	NameInput,
	NameObject,
	ParseCertificateChainResult,
	ParseCertificateErrorCode,
	ParseCertificateFailure,
	ParseCertificateResult,
	ParseCertificateSigningRequestErrorCode,
	ParseCertificateSigningRequestFailure,
	ParseCertificateSigningRequestResult,
	ParsedBitFlags,
	ParsedCertificate,
	ParsedCertificateSigningRequest,
	ParsedDistributionPoint,
	ParsedDistributionPointName,
	ParsedExtension,
	ParsedName,
	ParsedNameAttribute,
	ParsedNameConstraintForm,
	ParsedRelativeDistinguishedName,
	ParseOptions,
	PolicyConstraints,
	PolicyInformation,
	PolicyMapping,
	PolicyMappings,
	PolicyQualifierInfo,
	RelativeDistinguishedNameInput,
	SelfSignedCertificateResult,
	SelfSignedKeySource,
	SubjectAltName,
	SubjectAltNameTextOptions,
	ValidityInput,
} from '#micro509/x509';
export {
	certificateFingerprint,
	certificateMatchesPrivateKey,
	compareDistinguishedNames,
	createCertificate,
	createCertificateSigningRequest,
	createSelfSignedCertificate,
	decodeExtension,
	decodeExtensionMap,
	decodeExtensions,
	defineExtensionDecoder,
	defineExtensionDecoderMap,
	distinguishedNameToString,
	findExtension,
	getSubjectPublicKey,
	getSubjectPublicKeyOrThrow,
	matchCertificatePrivateKey,
	parseCertificateChainPem,
	parseCertificateChainPemOrThrow,
	parseCertificateDer,
	parseCertificateDerOrThrow,
	parseCertificateFromSource,
	parseCertificatePem,
	parseCertificatePemOrThrow,
	parseCertificateSigningRequestDer,
	parseCertificateSigningRequestDerOrThrow,
	parseCertificateSigningRequestPem,
	parseCertificateSigningRequestPemOrThrow,
	parseCertificatesFromSource,
	parseDistinguishedNameDer,
	relativeDistinguishedNameToString,
	subjectAltNameLabel,
	subjectAltNameToString,
} from '#micro509/x509';
