name: autofix.ci
on: { push: { branches: ["master"] }, pull_request: null, workflow_call: null }
permissions: { contents: read }
jobs:
  autofix:
    if: ${{ github.actor != 'autofix-ci[bot]' && !contains(github.event.head_commit.message, '[autofix.ci]') }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - { uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1, with: { persist-credentials: false } } # v7
      - { uses: $/.github/actions/setup-ts, with: { install-bun: "true" } }
      - uses: kjanat/install-dprint@43ace6752278feeb7c40262e29286b6342e33865 # v2
      - run: dprint config update -yr
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      - run: dprint fmt --allow-no-files --diff --excludes .github
      - run: bunx @biomejs/biome check --fix
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
